### PR TITLE
Emmo units

### PR DESCRIPTION
**Pull request by jesper-friis**
This pull request should be review and discussed before accepted. It adds two new domain ontologies: 
  * domains/emmo-units.owl: only base units and corresponding physical quantities. Imported in emmo.owl. 
  * domains/emmo-si-units.owl: provides some common SI units, physical quantities and physical constants using the relations introdused in emmo-units. Is NOT imported in emmo.owl since it slows down the reasoner. 

Included in domains/emmo-units.owl:
  * PhysicalQuantity subclasses:
      - BaseQuantity (with the 7 base SI quantities as subclasses)
      - DerivedQuantity
      - DimensionlessQuantity (with subclasses: PlaneAngle, SolidAngle)
      - PhysicalConstant
  * MeasurementUnit subclasses:
      - BaseUnit
      - DerivedUnit
      - DimensionlessUnit (with subclasses: PrefixUnit, Radian, Steradian, Unitless)
  * object properties:
      - hasPhysicalDimension (+ 3 subrelations) allowing to relate derived quantities to base quantities (e.g. velocity is length/time). These relations are intended to use with cardinality restrictions (could that slow down the reasoner?)
      - hasUnit whos inverse relates a unit to its corresponding physical property

Food for discussion
-------------------------
  * Does the categorisation provided with emmo-units make sense?
  * Relations for unit conversions have been dropped. Instead we will enable unit conversion by linking EMMO units to their corresponding unit in QUDT. Is it good enough to use annotation properties for that?

### CODE REVIEW

**Comment by emanueleghedini** [comment]
There are several important issues in this domain ontology, mostly related to the non respect of nominalistic nature of the EMMO (e.g. all the individuals listed should be classes), the differences between semiotic and mereotopologic branch (e.g. has_unit should be a has_part subclass, not a semiotic relation), the inconsistency of the axioms (e.g. HermiT reasoner claim it as inconsist while FaCT++ is extremely slow).

The main issue is that a measurement, and then a measurement unit, is represented in the EMMO as a formal language.

It is recommended, before merging to the v1.0.0 development branch, to revise it and to use as base for the emmo-unit the emmo-physical.properties-example.owl in the EMMO-examples repository.

**Comment by jesper-friis** [comment]
Thanks for the comments. I have changed hasUnit and hasPhysicalDimension to subrelations of hasSpatialPart. But I have little more problem problem with changing all individuals to classes.

The point of a unit system is to provide a common standard, hence there should e.g. only be one metre, which makes it a good candidate for an individual. But using the definition of the base units, I see that it is possible to define them as classes, whose individuals are particular measurements according to the definition. For example, a metre individual, is the distance I will obtain from a particular measurement of how far light will travel in vacuum during 1/299792458 of a second. Is this how I should think?

What about unit prefixes, how can they not just be named individuals of Number? 
Physical constants seems also natural to consider as individuals. Speed of light is e.g. an individual of velocity.

It also complicate unit conversions. With units being classes, it is as far as I know, not possible to assign data properties to them. Hence, we can no longer use the `has_conversion_multiplier` and `has_conversion_offset` data properties for unit conversion. Are there other ways? 

The only possibility I can think about is to use value restrictions, like

    Hour hasConversionMultiplier value second_per_hour
    Hour hasConversionOffset value zero

where `second_per_hour` and `zero` are individuals of `Real` with value 3600 and 0, respectively. However, this still involve individuals. Are there better ways? 

Unit conversions are important for low level interoperability, so it would be good if we can provide a standard way to do it with EMMO.

**Comment by emanueleghedini** [comment]
- Don't think that hasPhysicalDimension is a mereotopological relation. When you write [W m-1 K-1] you have no dimensional parts, but only unit parts! You say that [m] is a unit with length dimensionality, meaning that the meter class is a subclass of a more general class of length units.

- Your example "a meter is the distance I will obtain from a particular measurement of how far light will travel in vacuum during 1/299792458 of a second" is correct. However, a meter is not the distance, but the symbol and sign that stand for a real world object that measured gives you the PhysicalProperty length equal to 1 meter.

- Since every measurement has a tolerance, it means that there is not only one meter in the sense of the object with length 1 m because a) you can't manufacture a precise 1m object and b) you will not be able to measure it as 1 m lengthy object at every measurement.

- In the past, the definition of meter as the length of the sample preserved in Paris, would have lead to a different ontologization.

- Phyisical constant are not unique. For example, the Boltzmann constant value changed and will change depending on the accuracy of the experimental techniques. The standard value will be updated. Also there may be different values coming from different standardization bodies. So, you can't fix the value of a constant in an individual, but you can create an individual pointing to a number that you've found on a paper, on a book, on standardization body document (e.g. SI). So you'll have several individuals for the Boltzmann constant according to different sources. The same holds for other constants. This is a powerful feature of the EMMO!

- the data properties should attached only to mathematical symbol (e.g. a real should always have a owl:real data)

- About conversion: do you think that OWL is the right place for implementing unit conversions mechanisms? I don't think so. The EMMO should point initially only to label the PhysicalProperty with the right measurement unit, and leave conversion to the applications.

**Comment by jesper-friis** [comment]
* We know that the dimension of any physical quantity is the product of the 7 base quantities (length, mass, time, ,,,) raised to integer powers (e.g. velocity = length^1 * time^-1). In this sense, I thought that we could say that any `PhysicalQuantity hasPart some BaseQuantity` and any `DerivedPhysicalQuantity hasProperPart some BaseQuantity`. But if this is to stretch parthood too far, it is fine for me to move `hasPhysicalQuantity` to the semiotic branch. Would that be better? My intention is only to express our knowledge about the relation between dimension of physical quantities. 

* I buy your argument for units and physical constants being classes. Regarding Boltzmann constant, with the update of the SI definition earlier this year, Kelvin is now defined from Boltzmann constant being exactly 1.380649×10−23 J/K. Hence, the value of Boltzmann constant will never change again. But it doesn't change your point, historically Boltzmann has had different values and should therefore not be an individual. 

* But I still want to argue that unit prefixes, kilo, nano, etc should be individuals. Agree? I also think that they should be included in a units domain ontology for EMMO, especially if we knowledge about unit conversions. Agree?

* Regarding unit conversions. I do not think OWL is the right tool for implementing the actual conversions. However, I think that it is possible to express our knowledge about how units relate to each other using OWL. Then other tools could use EMMO to perform the actual conversions. The question is whether we want to include this knowledge in EMMO? 
If so, should we then use value restrictions? 
There are many unit ontologies out there that provide this information (the review article http://www.semantic-web-journal.net/system/files/swj1708.pdf discuss and compares some of them). If we don't provide unit conversions, we could at least link (using owl:sameAs) to other ontologies doing that, such that users can access to this information from EMMO. 

* Linking to other ontologies using owl:sameAs is also important for interoperability reasons, as pointed out by Thomas Hagelien. Do you have any preference for which ontology(s) we should refer to?

**Comment by jesper-friis** [comment]
I reopened the pull request, since the v1.0.0 branch contains an outdated version of domains/emmo-units.owl.

**Comment by jesper-friis** [comment]
To not reinvent the wheel it might be a good idea to refer to other ontologies, like QUDT, for unit conversions. Since units are classes in EMMO but individuals in QUDT, I think that annotation properties are the right way to express that. Right?

Are the skos:closeMatch or skos:exactMatch the right annotation properties to use?

**Comment by ahashibon** [comment]
@jesper-friis thanks for this pull request. looks good. As for relations between units, especially the derived ones, the math ontology from marketplace project should be quite useful. for now, it may be sufficient to simply have a place holder for,  either like you suggest (e.g., rdfs:definedB), or add a "DerivedFrom" as a subclass of "has_part" relation, is there a reason not to do so now? 

> But if this is to stretch parthood too far, it is fine for me to move hasPhysicalQuantity to the semiotic branch.

why does it stretch the parthood to say that "m^3" has part "m" for example? 

moreover, woudn't it be easier to just create an emmo-unit module and load it into the ontology rather that put it in the base?

**Comment by ahashibon** [comment]
#34 is one thing blocking this pull.

**Comment by jesper-friis** [comment]
Since both datatypes and units are needed on the atomistic domain ontology (and I can't have both branches checked out at the same time) I have moved the development to [https://github.com/jesper-friis/emmo-units](https://github.com/jesper-friis/emmo-units). 

I think that the emmo-units ontology should be in EMMO/domains, since it provides the basic framework for units. It is more a question whether the emmo-si-units ontology should be loaded by default, or be an optional addition. The issue I had with reasoning in the first version is now fixed, so that is not an issue any more.

**Comment by GeorgFerdinandSchneider** [comment]
Hi!

Interesting branch and effort in this pull request. As pointed out by @jesper-friis [above](https://github.com/emmo-repo/EMMO/pull/15#issuecomment-574179923) it certainly should be considered to reuse existing ontologies covering the domains of units. In addition to QUDT I like to point to [OM ontology](https://github.com/HajoRijgersberg/OM). For the definition of basic datatypes the [BasicDatatypeOntology (BDO)](https://github.com/TechnicalBuildingSystems/Ontologies/blob/master/BasicDataTypeOntology/ontology.ttl) formalises basic datatypes from XML in OWL 2.

**Pull request closed without merging**
