### PR TITLE
update to w3id.org

### PR DESCRIPTION
**Pull request by jsimonclark**
updates the IRIs to use the w3id.org PURL namespace. 

I also updated anywhere the emmo.info namespace occurred in the supporting files (e.g. python scripts, etc.). I checked and confirmed that

- [x] EMMO imports all its dependencies successfully
- [x] EMMO reasons successfully
- [x] The redirection rules work for the IRIs and the ontology itself

### CODE REVIEW

**Review by jesper-friis — APPROVED** [review]
A straight forward and consistent change of all IRIs - very nice!

As with the PR from Otello, I think that we should make a new release before applying it.

**Comment by jsimonclark** [comment]
I agree. Let's aim to merge it on Thursday and update to beta6. @hothello , do you have any comments?

**Comment by jesper-friis** [comment]
Please note: this branch is merged in to 1.0.0-beta7.

The PR is only kept here for reference.

**Comment by jesper-friis** [comment]
Closing - already merged into 1.0.0-beta7 and 1.0.0-final-dev-branch

**Pull request closed without merging**
