### PR TITLE
Add a few additional quantities and units

### PR DESCRIPTION
**Pull request by jesper-friis**
Added a few additional quantities needed by the crystallography, atomistic and microstructure domain ontologies.

Added quantities:
- MagneticDipoleMomentDimension
- PotentialEnergy
- KineticEnergy
- InternalEnergy
- VolumeFraction
- Torque
- Strain
- ReciprocalLength

Added constants:
- ElectronCharge

Added units:
- MetrePerSecond
- SquareMetre
- CubicMetre
- NewtonMetre
- ColumnMetre

Added dimensions
- VelocityDimension

### CODE REVIEW

**Comment by jesper-friis** [comment]
Removed duplication of inductance

**Review by francescalb — COMMENTED** [review]
PotentialEnergy, KineticEnergy, InternalEnergy, Torque, MagneticDipoleMoment, MagneticFieldStrength, Momentum are in middle/units_extension and not in isq.
Is this correct? 

Some Dimensions are in isq (e.g. LengthDimension), and others in units_extensions (at least AreaDimension and VolumeDimension)

**Comment by jesper-friis** [comment]
Good point. All quantities defined in ISO/IEC 80000 and should go into isq - that includes those you mention. That should be fixed before merging.

**Comment by emanueleghedini** [comment]
Actually EngineeredMaterial is part of Material subclasses, and should not moved to manufacturing.owl.
The axioms relating EngineerdMaterial to manufacturing process and making it a subclass of Engineered objects are introduced in manufacturing.owl, as an intergration.

**Comment by jesper-friis** [comment]
OK. I reverted the commit moving EngineeredMaterial to manufacturing.owl. 

We will then have to update the namespace check to ignore the integration in manufacturing.owl - I will do that later

**Pull request merged**
