### PR TITLE
Standard annotations; issue #68

### PR DESCRIPTION
**Pull request by jesper-friis**
Work in progress - don't merge yet

Added a few standard annotations from Dublin Core and SKOS ontologies. See issue #68 

The following annotation properties from Dublin Core are included for describing EMMO itself:
  - dcterms:title
  - dcterms:abstract
  - dcterms:creator
  - dcterms:contributor
  - dcterms:license

The following annotation properties from SKOS are intended to describe the ontological entities:
  - skos:prefLabel
  - skos:altLabel
  - skos:hiddenLabel

### CODE REVIEW

**Comment by jesper-friis** [comment]
We agreed to:
- not use skos:note since it is not a subproperty of rdfs:comment
- if we use skos:altLabel we should also use skos:prefLabel and skos:hiddenLabel
- make them explicit subproperties of rdfs:label
- replace all labels in EMMO with skos:prefLabel. This requires that users set up protege to render with prefLabel
- use dcterms for bibliographic annotations of EMMO as a whole

**Comment by jesper-friis** [comment]
top/annotations.owl is now updated according what we agreed above. 

Applying these updated annotations will make changes allover the repository - so we will not do that before the other remaining pull requests have been merged to to avoid difficult-to-resolve conflicts.

**Comment by jesper-friis** [comment]
The header of all ontologies has now been updated to use dcterms

All rdfs:label's have now been replaced with skos:prefLabel

**Comment by jesper-friis** [comment]
I think this should be ready to merge. But please doublecheck

**Comment by jesper-friis** [comment]
Correct IRIs in units-extension

http://emmo.info/middle/units-extension  -->  http://emmo.info/emmo/middle/units-extension

**Comment by jesper-friis** [comment]
I have double-checked the IRIs and I think they are correct now. 

However, in Sec. 5.1 of the [Dublin Core Guidelines](https://www.dublincore.org/specifications/dublin-core/dc-citation-guidelines/) they seem to recommend that we change the author list to several dcterms:creator (author) dcterms:contributor (affiliation) fields, like: 

    <dcterms:creator>Emanuele Ghedini</dcterms:creator>
    <dcterms:contributor>University of Bologna, IT</dcterms:contributor>
    <dcterms:creator>Gerhard Goldbeck</dcterms:creator>
    <dcterms:contributor>Goldbeck Consulting Ltd (UK)</dcterms:contributor>
    ...

Should we do that? We will loose the direct link between author and affiliation. Should we also add EMMC ASBL as dcterms:publisher?

**Review by francescalb — COMMENTED** [review]
Changes in labels look correct, but there are unresolved conflicts that need to be checked

**Comment by jesper-friis** [comment]
Thanks Francesca for an excellent review and fixing several mistakes. The conflicts are unfortunately messy, so this PR is replaced with #90.

**Pull request closed without merging**
