### PR TITLE
SimDOME to EMMO

### PR DESCRIPTION
**Pull request by emanueleghedini**
SimDOME proposed changes to the mid-level EMMO modules, mainly materials, manufacturing and physicalistic.

### CODE REVIEW

**Comment by jesper-friis** [comment]
Would it make sense to add the following restrictions:

    Device inverse(hasProperParticipant) some DiscreteManufacturing
    ManufacturedMaterial inverse(hasProperParticipant) some ContinuousManufacturing

**Comment by jesper-friis** [comment]
For a manufactured material, like an alloy. Can standard parthood be used to say it is 99% Al, 0.5% Mg and 0.5% Si?

**Comment by jesper-friis** [comment]
Shouldn't NaturalMaterial be defined in materials.owl rather than in manufacturing.owl?

EngeneeredMaterial is referred to in both manufacturing.owl and material.owl, but neither of them are importing the other. In my view materials is more fundamental than manufacturing, so I would suggest that manufacturing should import material. In that case should EngeneeredMaterial also be moved to materials.owl.

**Comment by jesper-friis** [comment]
I think that the classes Argon, Hydrocarbon (+ subclasses), Nitrogen (+ subclass) better belong to a domain ontology rather than in  EMMO middle. 

I am unsure about NanoMaterial and NanoParticle. To be in EMMO middle they should be annotated.

**Comment by jesper-friis** [comment]
Very nice distinction between PhaseOfMatter and StateOfMatter, but StateOfMatter is not annotated.

**Review by jesper-friis — COMMENTED** [review]
Looks good. But see the comments under conversation.

**Comment by emanueleghedini** [comment]
> For a manufactured material, like an alloy. Can standard parthood be used to say it is 99% Al, 0.5% Mg and 0.5% Si?

No. That type of information comes from a property. 
Parthood is a non quantitative relation. You can say through a parthood relation that you have for sure some Al atoms, but not how many.

**Comment by emanueleghedini** [comment]
> I think that the classes Argon, Hydrocarbon (+ subclasses), Nitrogen (+ subclass) better belong to a domain ontology rather than in EMMO middle.
> I am little unsure about NanoMaterial and NanoParticle, but think that they would be useful to have in EMMO-middle. They should just be annotated.
> I like the ontologisation of fluids and mixtures, but several classes are missing annotations. Maybe AcqueousSolution could be moved to a domain ontology.

You're right. I added them (Argon, Nitrogen) only as examples of classes types, to show that N2 (molecule) and NitrogesGas (gas) are different types of the same Nitrogen (material).

I think it's very important to underline that. If you agree we can create a domain ontology with these examples.

I will add annotations and update the branch soon.

**Comment by jesper-friis** [comment]
Yes, I think it would be very helpful to create a domain ontology with Argon, Nitrogen etc.

**Comment by emanueleghedini** [comment]
> Shouldn't NaturalMaterial be defined in materials.owl rather than in manufacturing.owl?
> 
> EngeneeredMaterial is referred to in both manufacturing.owl and material.owl, but neither of them are importing the other. In my view materials is more fundamental than manufacturing, so I would suggest that manufacturing should import material. In that case should EngeneeredMaterial also be moved to materials.owl.

I agree that material.owl is comes before manufacturing. 

However, the need for a definition of natural material comes only when you define a non-natural (manufactured) material.

We can introduce in manufacturing.owl the axiom stating that Material is a disjoint union of NaturalMaterial and EngineeredMaterial.

**Review by jesper-friis — APPROVED** [review]
The remaining annotations can be added after merge.

**Comment by emanueleghedini** [comment]
I think I've fulfilled all requests.

Going to merge.

**Pull request merged**
